FROM  pytorch/pytorch:1.8.0-cuda11.1-cudnn8-runtime
RUN apt update && apt install build-essential libsm6 libxext6 git vim -y
ADD requirements.txt /tmp/

RUN apt update && apt install -y build-essential ffmpeg libsm6 libxext6 git vim \
    && python -m pip install --upgrade pip \
    && pip install --no-cache-dir -r /tmp/requirements.txt \
    && pip install --no-cache-dir importlib-metadata==4.13.0 --force-reinstall \
    && apt-get purge -y build-essential \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && conda install -c conda-forge pybind11 \
    && apt update && apt-get install -y cmake g++ wget

ARG CACHEBUST=1

RUN pip install --force-reinstall --no-deps git+https://github.com/AIRI-Institute/pogema.git
